### ISSUE TITLE
No output file generated.

### ISSUE THREAD

**Issue by Humaira-Rana** [raysworld/Xef2Mat#2]
I have executed the .exe. file and the status shows completed. But no output file appear in the output folder. I want to know that should i install kinect SDK and its tools before executing its file.

**Comment by raysworld** [comment]
Hi, yes. Kinect SDK should be installed first before execution. And it is recommended you compile from the source code to make sure if it works.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Humaira-Rana<mailto:notifications@github.com>
发送时间: 2017年9月12日 17:23
收件人: raysworld/Xef2Mat<mailto:Xef2Mat@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [raysworld/Xef2Mat] No output file generated. (#2)


I have executed the .exe. file and the status shows completed. But no output file appear in the output folder. I want to know that should i install kinect SDK and its tools before executing its file.

―
