### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Kompalk** [raysworld/Xef2Mat#3]
I have tried using Xef2Mat...although its working fine ..but i am unable to compare my .mat file with .xef file...please help

**Comment by raysworld** [comment]
Hi Kompalk, can you let me know what you mean 'compare' the .mat file and the .xef file?

**Comment by Kompalk** [comment]
In what fashion the values are stored in .mat file..in what way they are
actually retrieved.

On 19-Feb-2018 6:10 AM, "raysworld" <notifications@github.com> wrote:

Hi Kompalk, can you let me know what you mean 'compare' the .mat file and
the .xef file?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/raysworld/Xef2Mat/issues/3#issuecomment-366563752>, or mute
the thread

**Comment by raysworld** [comment]
Maybe you could find some docs about the .mat format from Matworks... I am afraid that this is not a related issue that should be discussed here...
